"""create_event_ticketing_tables

Revision ID: 027855a270a0
Revises: 230bcf4c565f
Create Date: 2026-10-08 09:22:35.810019+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '027855a270a0'
down_revision: Union[str, None] = '230bcf4c565f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=False),
    sa.Column('venue_address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gates_open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restrictions', sa.String(length=255), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SOLD_OUT', 'COMPLETED', 'CANCELLED', name='event_status_enum'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('ticket_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('max_per_booking', sa.Integer(), nullable=False),
    sa.Column('sale_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_types_event_id'), 'ticket_types', ['event_id'], unique=False)
    op.create_table('event_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_paise', sa.Integer(), nullable=False),
    sa.Column('total_amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'REFUNDED', name='event_booking_status_enum'), nullable=False),
    sa.Column('payment_gateway', sa.String(length=50), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('refund_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_bookings_booking_reference'), 'event_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_event_bookings_customer_email'), 'event_bookings', ['customer_email'], unique=False)
    op.create_index(op.f('ix_event_bookings_event_id'), 'event_bookings', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_bookings_razorpay_order_id'), 'event_bookings', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_event_bookings_razorpay_payment_id'), 'event_bookings', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_event_bookings_status'), 'event_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_event_bookings_ticket_type_id'), 'event_bookings', ['ticket_type_id'], unique=False)
    op.create_index(op.f('ix_event_bookings_user_id'), 'event_bookings', ['user_id'], unique=False)
    op.create_table('event_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=64), nullable=False),
    sa.Column('attendee_name', sa.String(length=255), nullable=False),
    sa.Column('attendee_phone', sa.String(length=50), nullable=True),
    sa.Column('qr_token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'CHECKED_IN', 'CANCELLED', 'REFUNDED', name='event_ticket_status_enum'), nullable=False),
    sa.Column('is_checked_in', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.UUID(), nullable=True),
    sa.Column('check_in_device_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['event_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_tickets_booking_id'), 'event_tickets', ['booking_id'], unique=False)
    op.create_index(op.f('ix_event_tickets_event_id'), 'event_tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_tickets_is_checked_in'), 'event_tickets', ['is_checked_in'], unique=False)
    op.create_index(op.f('ix_event_tickets_qr_token'), 'event_tickets', ['qr_token'], unique=True)
    op.create_index(op.f('ix_event_tickets_status'), 'event_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_event_tickets_ticket_number'), 'event_tickets', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_event_tickets_ticket_type_id'), 'event_tickets', ['ticket_type_id'], unique=False)
    op.create_table('ticket_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['event_bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['event_tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_audit_logs_action'), 'ticket_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_ticket_audit_logs_booking_id'), 'ticket_audit_logs', ['booking_id'], unique=False)
    op.create_index(op.f('ix_ticket_audit_logs_ticket_id'), 'ticket_audit_logs', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_audit_logs_ticket_id'), table_name='ticket_audit_logs')
    op.drop_index(op.f('ix_ticket_audit_logs_booking_id'), table_name='ticket_audit_logs')
    op.drop_index(op.f('ix_ticket_audit_logs_action'), table_name='ticket_audit_logs')
    op.drop_table('ticket_audit_logs')
    op.drop_index(op.f('ix_event_tickets_ticket_type_id'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_ticket_number'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_status'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_qr_token'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_is_checked_in'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_event_id'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_booking_id'), table_name='event_tickets')
    op.drop_table('event_tickets')
    op.drop_index(op.f('ix_event_bookings_user_id'), table_name='event_bookings')
    op.drop_index(op.f('ix_event_bookings_ticket_type_id'), table_name='event_bookings')
    op.drop_index(op.f('ix_event_bookings_status'), table_name='event_bookings')
    op.drop_index(op.f('ix_event_bookings_razorpay_payment_id'), table_name='event_bookings')
    op.drop_index(op.f('ix_event_bookings_razorpay_order_id'), table_name='event_bookings')
    op.drop_index(op.f('ix_event_bookings_event_id'), table_name='event_bookings')
    op.drop_index(op.f('ix_event_bookings_customer_email'), table_name='event_bookings')
    op.drop_index(op.f('ix_event_bookings_booking_reference'), table_name='event_bookings')
    op.drop_table('event_bookings')
    op.drop_index(op.f('ix_ticket_types_event_id'), table_name='ticket_types')
    op.drop_table('ticket_types')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
