import os
import sys
import time
import subprocess
import shutil
import boto3
import asyncio
import asyncpg
from pathlib import Path
from dotenv import load_dotenv

# Load environment configuration from apps/backend/.env or root .env
env_path = Path(__file__).resolve().parent.parent / "apps" / "backend" / ".env"
if env_path.exists():
    load_dotenv(env_path)
else:
    load_dotenv()

R2_ENDPOINT = os.getenv("R2_ENDPOINT_URL", "")
R2_KEY_ID = os.getenv("R2_ACCESS_KEY_ID", "")
R2_SECRET = os.getenv("R2_SECRET_ACCESS_KEY", "")
R2_BUCKET = os.getenv("R2_STREAMING_BUCKET", "v19plus-r2-backend")
CDN_BASE = os.getenv("CDN_STREAMING_BASE_URL", "https://pub-2b3faff7804a4ba8b00830cca1749352.r2.dev").rstrip("/")
DB_URL = os.getenv("DATABASE_SYNC_URL") or os.getenv("DATABASE_URL", "")
if "+asyncpg" in DB_URL:
    DB_URL = DB_URL.replace("+asyncpg", "")

SOURCE_KEY = "b8d4b8e2_EP-02.mov"
SOURCE_URL = f"{CDN_BASE}/{SOURCE_KEY}"
LOCAL_MASTER = "/tmp/master_ep02.mov"
OUTPUT_DIR = "/tmp/hls_ep02"
TARGET_PREFIX = "hls/second-task-race-to-the-finish"
CONTENT_SLUG = "second-task-race-to-the-finish"


def log(msg: str):
    print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {msg}", flush=True)


def download_master():
    log(f"📥 Step 1: Downloading 19.34 GB master from Cloudflare R2 ({SOURCE_URL})...")
    cmd = [
        "curl",
        "-L",
        "-C", "-",
        "--retry", "50",
        "--retry-delay", "2",
        "--retry-max-time", "0",
        "--keepalive-time", "10",
        "-A", "Mozilla/5.0",
        "-o", LOCAL_MASTER,
        SOURCE_URL,
    ]
    attempts = 0
    while attempts < 50:
        attempts += 1
        res = subprocess.run(cmd)
        if res.returncode == 0:
            break
        curr_mb = os.path.getsize(LOCAL_MASTER) / (1024 * 1024) if os.path.exists(LOCAL_MASTER) else 0
        log(f"⚠️ Connection interrupted (code {res.returncode}) at {curr_mb:.1f} MB. Resuming download in 2s (attempt {attempts}/50)...")
        time.sleep(2)

    if not os.path.exists(LOCAL_MASTER) or os.path.getsize(LOCAL_MASTER) < 18 * 1024 * 1024 * 1024:
        raise RuntimeError("Master file was not completely downloaded.")

    file_size_mb = os.path.getsize(LOCAL_MASTER) / (1024 * 1024)
    log(f"✅ Download complete! Size: {file_size_mb:.1f} MB ({file_size_mb/1024:.2f} GB)")


def transcode_to_hls():
    log("🎬 Step 2: Transcoding 8K master to Adaptive HLS (1080p, 720p, 480p) via VideoToolbox hardware acceleration...")
    if os.path.exists(OUTPUT_DIR):
        shutil.rmtree(OUTPUT_DIR, ignore_errors=True)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(os.path.join(OUTPUT_DIR, "1080p"), exist_ok=True)
    os.makedirs(os.path.join(OUTPUT_DIR, "720p"), exist_ok=True)
    os.makedirs(os.path.join(OUTPUT_DIR, "480p"), exist_ok=True)

    cmd = [
        "ffmpeg",
        "-y",
        "-hwaccel", "videotoolbox",
        "-i", LOCAL_MASTER,
        "-filter_complex",
        "[0:v]scale=w=1920:h=1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2[v1080];"
        "[0:v]scale=w=1280:h=720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2[v720];"
        "[0:v]scale=w=854:h=480:force_original_aspect_ratio=decrease,pad=854:480:(ow-iw)/2:(oh-ih)/2[v480]",
        "-map", "[v1080]", "-map", "0:a:0?",
        "-c:v:0", "h264_videotoolbox", "-b:v:0", "4000k", "-maxrate:v:0", "4500k", "-bufsize:v:0", "8000k",
        "-c:a:0", "aac", "-b:a:0", "192k", "-ac:a:0", "2",
        "-map", "[v720]", "-map", "0:a:0?",
        "-c:v:1", "h264_videotoolbox", "-b:v:1", "2200k", "-maxrate:v:1", "2600k", "-bufsize:v:1", "4400k",
        "-c:a:1", "aac", "-b:a:1", "128k", "-ac:a:1", "2",
        "-map", "[v480]", "-map", "0:a:0?",
        "-c:v:2", "h264_videotoolbox", "-b:v:2", "900k", "-maxrate:v:2", "1100k", "-bufsize:v:2", "1800k",
        "-c:a:2", "aac", "-b:a:2", "96k", "-ac:a:2", "2",
        "-g", "48",
        "-keyint_min", "48",
        "-sc_threshold", "0",
        "-f", "hls",
        "-hls_time", "4",
        "-hls_playlist_type", "vod",
        "-hls_flags", "independent_segments",
        "-master_pl_name", "master.m3u8",
        "-var_stream_map", "v:0,a:0,name:1080p v:1,a:1,name:720p v:2,a:2,name:480p",
        "-hls_segment_filename", os.path.join(OUTPUT_DIR, "%v/seg_%04d.ts"),
        os.path.join(OUTPUT_DIR, "%v/playlist.m3u8"),
    ]

    log("Running FFmpeg transcode command...")
    res = subprocess.run(cmd)
    if res.returncode != 0:
        raise RuntimeError(f"FFmpeg transcoding failed with code {res.returncode}")

    master_m3u8 = os.path.join(OUTPUT_DIR, "master.m3u8")
    if not os.path.exists(master_m3u8):
        raise FileNotFoundError("master.m3u8 was not generated by FFmpeg.")
    log("✅ Transcoding to HLS complete!")


def upload_hls_to_r2():
    log(f"☁️ Step 3: Uploading transcoded HLS directory to Cloudflare R2 ({R2_BUCKET}/{TARGET_PREFIX})...")
    s3 = boto3.client(
        "s3",
        endpoint_url=R2_ENDPOINT,
        aws_access_key_id=R2_KEY_ID,
        aws_secret_access_key=R2_SECRET,
        region_name="auto",
    )

    total_files = 0
    for root, _, files in os.walk(OUTPUT_DIR):
        for f in files:
            file_path = os.path.join(root, f)
            rel_path = os.path.relpath(file_path, OUTPUT_DIR)
            s3_key = f"{TARGET_PREFIX}/{rel_path}"

            content_type = "video/mp2t"
            if f.endswith(".m3u8"):
                content_type = "application/vnd.apple.mpegurl"
            elif f.endswith(".vtt"):
                content_type = "text/vtt"

            s3.upload_file(
                file_path,
                R2_BUCKET,
                s3_key,
                ExtraArgs={"ContentType": content_type},
            )
            total_files += 1
            if total_files % 50 == 0:
                log(f"Uploaded {total_files} segments...")

    log(f"✅ Successfully uploaded {total_files} HLS files to Cloudflare R2!")


async def update_database():
    log(f"💾 Step 4: Updating PostgreSQL database record for '{CONTENT_SLUG}'...")
    final_hls_url = f"{CDN_BASE}/{TARGET_PREFIX}/master.m3u8"
    conn = await asyncpg.connect(DB_URL)
    row = await conn.fetchrow(
        """
        UPDATE content
        SET hls_manifest_key = $1, status = 'PUBLISHED', updated_at = NOW()
        WHERE slug = $2
        RETURNING id, title, hls_manifest_key
        """,
        final_hls_url,
        CONTENT_SLUG,
    )
    await conn.close()
    if row:
        log(f"✅ Database updated successfully! Title: {row['title']}, Manifest: {row['hls_manifest_key']}")
    else:
        log(f"⚠️ Warning: Could not find content with slug '{CONTENT_SLUG}'")


def cleanup(success: bool):
    log("🧹 Step 5: Cleaning up local temporary files...")
    if success and os.path.exists(LOCAL_MASTER):
        os.remove(LOCAL_MASTER)
        log("Deleted master file from /tmp")
    if os.path.exists(OUTPUT_DIR):
        shutil.rmtree(OUTPUT_DIR, ignore_errors=True)
        log("Deleted HLS output dir from /tmp")


def main():
    log("🚀 Starting V19Plus Option B Automated Transcode & Ingest Pipeline...")
    success = False
    try:
        download_master()
        transcode_to_hls()
        upload_hls_to_r2()
        asyncio.run(update_database())
        success = True
        log("🎉 ALL STEPS FINISHED! Video is now 100% ready for seamless streaming with zero buffering!")
    except Exception as e:
        log(f"❌ Error during processing: {e}")
        import traceback
        traceback.print_exc()
    finally:
        cleanup(success)


if __name__ == "__main__":
    main()
