import asyncio
import os
import re
from typing import Any, Callable, Coroutine, Dict, List


class FFmpegTranscoder:
    def __init__(self, input_path: str, output_dir: str, duration: float):
        self.input_path = input_path
        self.output_dir = output_dir
        self.duration = duration
        os.makedirs(output_dir, exist_ok=True)

    def _parse_time_to_seconds(self, time_str: str) -> float:
        parts = time_str.split(":")
        if len(parts) == 3:
            h, m, s = parts
            return float(h) * 3600 + float(m) * 60 + float(s)
        return 0.0

    async def transcode_to_hls(
        self,
        ladder: List[Dict[str, Any]],
        on_progress: Optional[Callable[[int], Coroutine[Any, Any, None]]] = None,
    ) -> str:
        """
        Execute single-pass multi-variant HLS transcoding command.
        Generates individual rendition playlists and unified master.m3u8.
        """
        cmd = [
            "ffmpeg",
            "-y",
            "-i", self.input_path,
        ]

        filter_complex_parts = []
        var_stream_map_parts = []

        for idx, rendition in enumerate(ladder):
            filter_complex_parts.append(
                f"[0:v]scale=w={rendition['width']}:h={rendition['height']}:force_original_aspect_ratio=decrease,pad={rendition['width']}:{rendition['height']}:(ow-iw)/2:(oh-ih)/2[v{idx}]"
            )

        cmd.extend(["-filter_complex", ";".join(filter_complex_parts)])

        # Rendition mappings and encoding options
        for idx, rendition in enumerate(ladder):
            cmd.extend([
                "-map", f"[v{idx}]",
                "-map", "0:a:0?",
                f"-c:v:{idx}", "libx264",
                f"-preset:v:{idx}", "fast",
                f"-crf:v:{idx}", "22",
                f"-maxrate:v:{idx}", rendition["maxrate"],
                f"-bufsize:v:{idx}", rendition["bufsize"],
                f"-c:a:{idx}", "aac",
                f"-b:a:{idx}", rendition["audio_bitrate"],
                f"-ac:a:{idx}", "2",
            ])
            var_stream_map_parts.append(f"v:{idx},a:{idx},name:{rendition['name']}")

        # HLS Packaging flags
        cmd.extend([
            "-g", "48",
            "-keyint_min", "48",
            "-sc_threshold", "0",
            "-f", "hls",
            "-hls_time", "6",
            "-hls_playlist_type", "vod",
            "-hls_flags", "independent_segments",
            "-master_pl_name", "master.m3u8",
            "-var_stream_map", " ".join(var_stream_map_parts),
            "-hls_segment_filename", os.path.join(self.output_dir, "%v/seg_%04d.ts"),
            os.path.join(self.output_dir, "%v/playlist.m3u8"),
        ])

        # Create rendition subdirectories
        for rendition in ladder:
            os.makedirs(os.path.join(self.output_dir, rendition["name"]), exist_ok=True)

        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )

        time_pattern = re.compile(r"time=(\d{2}:\d{2}:\d{2}\.\d+)")
        last_reported_pct = 0

        while True:
            line = await proc.stderr.readline()
            if not line:
                break
            line_str = line.decode("utf-8", errors="ignore")
            match = time_pattern.search(line_str)
            if match and self.duration > 0:
                current_secs = self._parse_time_to_seconds(match.group(1))
                progress_pct = min(99, int((current_secs / self.duration) * 100))
                if progress_pct > last_reported_pct and on_progress:
                    last_reported_pct = progress_pct
                    await on_progress(progress_pct)

        await proc.wait()

        if proc.returncode != 0:
            raise RuntimeError(f"FFmpeg transcoding failed with exit code {proc.returncode}")

        if on_progress:
            await on_progress(100)

        master_path = os.path.join(self.output_dir, "master.m3u8")
        if not os.path.exists(master_path):
            raise FileNotFoundError("master.m3u8 was not generated by FFmpeg.")

        return master_path
